---

- hosts: eric_cluster
  vars:
    oracle_java_download_url: "http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.rpm"
    oracle_java_install_name: "jdk1.8.0_112"
    oracle_java_rpm_filename: "jdk-8u112-linux-x64.rpm"
  remote_user: root
  pre_tasks:
  - name: disable selinux
    selinux: state=disabled
  - name: disable IPv6 all
    sysctl: 
        name: net.ipv6.conf.all.disable_ipv6 
        value: 1 
        state: present
  - name: disable IPv6 default
    sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
  - name: disable swappiness 
    sysctl: name=vm.swappiness value=1 state=present
  - name: Install packages
    yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
    with_items:
      - { name: 'ntp', state: 'present' }
  - name: download java
    command: "wget -q -O {{ ansible_env.HOME }}/{{oracle_java_rpm_filename}} --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' {{ oracle_java_download_url }} creates={{oracle_java_rpm_filename}}"
  - name: Install oracle java
    yum: 
        name: "{{ ansible_env.HOME }}/{{oracle_java_rpm_filename}}"
        state: "present"

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "/usr/java/{{oracle_java_install_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path="{{ ansible_env.HOME }}/{{oracle_java_rpm_filename}}"

#  - name: Download Java
#    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

#  roles:
#  - { role: ansiblebit.oracle-java, oracle_java_rpm_url: 'http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.rpm', oracle_java_rpm_filename: jdk-8u112-linux-x64.rpm, oracle_java_version: 8, oracle_java_version_update: 112, oracle_java_version_build: 15, oracle_java_set_as_default: yes }
#  - { role: dalekurt.java8, download_url: 'http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.rpm', java_name: "{{download_folder}}/jdk1.8.0_112", 
# java_archive: "{{download_folder}}/jdk-8u45-linux-x64.tar.gz" oracle_java_rpm_filename: jdk-8u112-linux-x64.rpm, oracle_java_version: 8, oracle_java_version_update: 112, oracle_java_version_build: 15, oracle_java_set_as_default: yes }