- hosts: cloudera
remote_user: root
tasks:
- selinux: state=disabled
- sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present
- sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
- sysctl: name=vm.swappiness value=0 state=present
- authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
- copy: src=/etc/hosts dest=/etc/hosts owner=root group=root mode=0644
